[general]
import = ["./themes/wallust.toml"]
live_config_reload = true
working_directory = "None"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14
offset.y = -1
# offset.x = -1

[font.normal]
family = "GohuFont"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
opacity = 0.75
padding = { x = 0, y = 0 }

[[keyboard.bindings]]
chars = "\u0018T"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018L"
key = "P"
mods = "Alt"

