[manager]
hovered       = { bg = "blue", bold = false }
border_symbol = "│"

[indicator]
padding = { open = "█", close = "█" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
